## 动态规划是最精妙的算法之一。主要的思想是找到transfer的条件。

## 背包问题 （见算法图解书）
特定重量和价值，找到最优装载办法

In [38]:
import numpy as np

def solve(vlist,wlist,totalW):
    n = len(vlist)
    w = totalW
    tab = np.zeros([n+1,w+1])
    for i in range(1,n+1):
        for j in range(1,w+1):
            if wlist[i-1]>j:
                tab[i][j]=tab[i-1][j]
            else:
                tab[i][j]=max(tab[i-1][j],tab[i-1][j-wlist[i-1]]+vlist[i-1])
    
    return tab

In [40]:
val = [10,3,9,5,6]
weights = [3,1,2,2,1]
print(solve(val,weights,6))

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. 10. 10. 10. 10.]
 [ 0.  3.  3. 10. 13. 13. 13.]
 [ 0.  3.  9. 12. 13. 19. 22.]
 [ 0.  3.  9. 12. 14. 19. 22.]
 [ 0.  6.  9. 15. 18. 20. 25.]]


## 最大子序列和， 第53题

In [52]:
def solve(list):
    n = len(list)
    pre = list[0]
    maxSum = list[0]
    for i in range(1,n):
        pre = max(list[i], pre+list[i])
        if pre>maxSum:
            maxSum = pre
   
    return maxSum


In [53]:
nums = [-2,1,-3,4,-1,2,1,-5,4]
print(solve(nums))

6


## 1269 - 留在原地的可能性
注意，虽然想到了动态规划。也想到了要利用前一步的已经算好的值。但是需要注意的是：我们应该维持一个表，记录每一步，最后停留在每一个位置的可能性。这样，最后一步回到位置0的办法就是上一步在位置0或是位置1的可能的和。

In [39]:
class Solution:
    def numWays(self, steps, arrLen):
        maxCol = min(steps, arrLen)
        l2 = [0]*maxCol
        l2[0] = 1
        mod = 10**9+7
        for i in range(steps):
            l1 = [0]*maxCol
            l1[0] = (l2[0]+l2[1])%mod
            l1[-1] = (l2[-1]+l2[-2])%mod            
            for j in range(1, maxCol-1):
                l1[j] = (l2[j-1]+l2[j]+l2[j+1])%mod
            l2 = l1
        return l1[0]
            

## 注意
上一题容易出错（其实是超时的原因）是，当arrLEN远远大于steps时，创立那么长的数列根本没用
所以，表的dim=1的长度只需要是step或是arrlen的较小值

