## 动态规划是最精妙的算法之一。主要的思想是找到transfer的条件。

## 背包问题 （见算法图解书）
特定重量和价值，找到最优装载办法

In [38]:
import numpy as np

def solve(vlist,wlist,totalW):
    n = len(vlist)
    w = totalW
    tab = np.zeros([n+1,w+1])
    for i in range(1,n+1):
        for j in range(1,w+1):
            if wlist[i-1]>j:
                tab[i][j]=tab[i-1][j]
            else:
                tab[i][j]=max(tab[i-1][j],tab[i-1][j-wlist[i-1]]+vlist[i-1])
    
    return tab

In [40]:
val = [10,3,9,5,6]
weights = [3,1,2,2,1]
print(solve(val,weights,6))

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. 10. 10. 10. 10.]
 [ 0.  3.  3. 10. 13. 13. 13.]
 [ 0.  3.  9. 12. 13. 19. 22.]
 [ 0.  3.  9. 12. 14. 19. 22.]
 [ 0.  6.  9. 15. 18. 20. 25.]]


## 最大子序列和， 第53题

In [52]:
def solve(list):
    n = len(list)
    pre = list[0]
    maxSum = list[0]
    for i in range(1,n):
        pre = max(list[i], pre+list[i])
        if pre>maxSum:
            maxSum = pre
   
    return maxSum


In [53]:
nums = [-2,1,-3,4,-1,2,1,-5,4]
print(solve(nums))

6
